version: '3.9'

services:
  backend:
    build:
      context: .
      target: dev
    image: backend
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/backend/src
      - ./tests:/usr/backend/tests
    depends_on:
      - db
