version: '3.9'

services:
  app:
    build:
      target: dev
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - db
      - test-db
      - redis

  db:
    env_file: .env
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
