version: '3.9'

services:
  backend:
    build:
      context: .
      target: dev
    image: backend
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./src:/usr/backend/src
      - ./tests:/usr/backend/tests
    depends_on:
      - db
