services:
  test-redis:
    image: bitnami/redis:8.0.3
    command:
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped

  stripe-api:
    image: stripe/stripe-mock:latest
