name: Docker build & deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [backend, clickhouse]
    steps:
      - run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (${{ matrix.image }})
        id: build-image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ${{ matrix.image == 'backend' && 'Dockerfile' || 'clickhouse/Dockerfile' }}
          tags: |
            ghcr.io/talodev/${{ matrix.image }}:latest
            ghcr.io/talodev/${{ matrix.image }}:${{ env.TAG }}
          target: ${{ matrix.image == 'backend' && 'prod' || '' }}

      - name: Image digest (${{ matrix.image }})
        run: echo ${{ steps.build-image.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Update backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_passphrase: ${{ secrets.PROXY_PASSPHRASE }}
          script: |
            cd /usr/talo
            ./scripts/update.sh
